=== JarLob/CrypTool2/CrypPlugins/Wizard/Config/wizard.dtd
<!ELEMENT category (name*, description*, headline*, task*, (category|input|sampleViewer|loadSample|file)*) >
<!ATTLIST category 
   image	CDATA #IMPLIED
>

<!ELEMENT input (name*, description*, headline*, task*, (inputBox|comboBox|checkBox|keyTextBox|pluginSetter|label)*, (category|input|sampleViewer|loadSample|file)?) >
<!ATTLIST input 
   image	CDATA #IMPLIED
>

<!ELEMENT sampleViewer (name*, description*, headline*, task*, (inputBox|comboBox|checkBox|keyTextBox|pluginSetter|label|outputBox|progressBar|presentation)*) >
<!ATTLIST sampleViewer 
   image	CDATA 	#IMPLIED
   file		CDATA       #REQUIRED
   showCreateButton		CDATA       #IMPLIED
>

<!ELEMENT loadSample (name*, description*) >
<!ATTLIST loadSample 
   file		CDATA       #REQUIRED
   title	CDATA       #REQUIRED
>

<!ELEMENT file EMPTY >
<!ATTLIST file 
   resource	CDATA       #REQUIRED
>

<!ELEMENT name (#PCDATA|condition)* >
<!ATTLIST name 
   lang	CDATA       "en"
>

<!ELEMENT description (#PCDATA|condition|b|i|u|newline|external)* >
<!ATTLIST description 
   lang	CDATA       "en"
>

<!ELEMENT headline (#PCDATA|condition)* >
<!ATTLIST headline 
   lang	CDATA       "en"
>

<!ELEMENT task (#PCDATA|condition)* >
<!ATTLIST task 
   lang	CDATA       "en"
>

<!ELEMENT b (#PCDATA|b|i|u|newline)* >
<!ELEMENT i (#PCDATA|b|i|u|newline)* >
<!ELEMENT u (#PCDATA|b|i|u|newline)* >
<!ELEMENT newline EMPTY >
<!ELEMENT external (#PCDATA|b|i|u|newline)* >
<!ATTLIST external 
   ref	CDATA       #REQUIRED
>

<!ELEMENT condition (#PCDATA|b|i|u|newline|external)* >
<!ATTLIST condition
   plugin		CDATA       #REQUIRED
   property		CDATA       #REQUIRED
   value	CDATA       #REQUIRED
>

<!ELEMENT inputBox (storage?, description+, defaultvalue*) >
<!ATTLIST inputBox 
   plugin		CDATA       #REQUIRED
   property		CDATA       #REQUIRED
   alignment	CDATA       #IMPLIED
   width		CDATA       #IMPLIED
   group		CDATA       #IMPLIED
   visibleLines	CDATA       #IMPLIED
   regex		CDATA       #IMPLIED
>

<!ELEMENT outputBox (storage?, description+) >
<!ATTLIST outputBox 
   plugin		CDATA       #REQUIRED
   property		CDATA       #REQUIRED
   alignment	CDATA       #IMPLIED
   width		CDATA       #IMPLIED
   group		CDATA       #IMPLIED
   visibleLines	CDATA       #IMPLIED
>

<!ELEMENT presentation (description+) >
<!ATTLIST presentation 
   plugin		CDATA       #REQUIRED
   alignment	CDATA       #IMPLIED
   width		CDATA       #IMPLIED
   height		CDATA       #IMPLIED
   group		CDATA       #IMPLIED
>

<!ELEMENT comboBox (description+, item+) >
<!ATTLIST comboBox 
   plugin		CDATA       #IMPLIED
   property		CDATA       #IMPLIED
   alignment	CDATA       #IMPLIED
   width		CDATA       #IMPLIED
   group		CDATA       #IMPLIED
   defaultValue	CDATA       #IMPLIED
>

<!ELEMENT checkBox (description+, content+) >
<!ATTLIST checkBox 
   plugin		CDATA       #REQUIRED
   property		CDATA       #REQUIRED
   alignment	CDATA       #IMPLIED
   width		CDATA       #IMPLIED
   group		CDATA       #IMPLIED
   defaultValue	CDATA       #IMPLIED
>

<!ELEMENT keyTextBox (storage?, description+) >
<!ATTLIST keyTextBox 
   plugin		CDATA       #REQUIRED
   property		CDATA       #REQUIRED
   format		CDATA       #REQUIRED
   defaultkey		CDATA       #IMPLIED
   alignment	CDATA       #IMPLIED
   width		CDATA       #IMPLIED
   group		CDATA       #IMPLIED
>

<!ELEMENT progressBar (description+) >
<!ATTLIST progressBar
   plugin		CDATA       #REQUIRED   
   alignment	CDATA       #IMPLIED
   width		CDATA       #IMPLIED
   group		CDATA       #IMPLIED
>

<!ELEMENT pluginSetter (#PCDATA) >
<!ATTLIST pluginSetter
   plugin		CDATA       #REQUIRED
   property		CDATA       #REQUIRED
>

<!ELEMENT label (description+) >
<!ATTLIST label
   alignment	CDATA       #IMPLIED
   group		CDATA       #IMPLIED
>

<!ELEMENT item (pluginSetter*) >
<!ATTLIST item 
   content	CDATA       #REQUIRED
   lang	CDATA       "en"
>

<!ELEMENT content (#PCDATA|condition)* >
<!ATTLIST content 
   lang	CDATA       "en"
>
<!ELEMENT defaultvalue (#PCDATA|condition)* >
<!ATTLIST defaultvalue 
   lang	CDATA       "en"
>

<!ELEMENT storage (#PCDATA) >
<!ATTLIST storage
   key	CDATA       #REQUIRED
   showStorageButton (true|false)       #IMPLIED
   showLoadAddButtons (true|false)       #IMPLIED
>

=== JarLob/CrypTool2/CrypPlugins/Wizard/Config/Indiv/wizard.config.indiv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE category SYSTEM "..\wizard.dtd"[]>
<!-- This is the XML file defining the individual procedures categories a user can select from. -->
<category image="Indiv">
  <name lang="en">Tools</name>
  <name lang="zh-CN">工具类</name>
  <name lang="ru">инструменты</name>
  <name lang="de">Werkzeuge</name>
  <description lang="en">Here you can quickly perform specific tasks, e.g. encryption of a message with a password or encoding text to base64.</description>
  <description lang="zh-CN">在这里，您可以快速执行特定任务，例如使用密码对消息加密或将文本编码为base64。</description>
  <description lang="ru">Здесь вы можете быстро выполнить определенные задачи, например, шифрование сообщения с паролем или текстом кодировки на base64.</description>
  <description lang="de">Hier können Sie schnell spezifische Aufgaben ausführen (z.B. Verschlüsseln eines Textes mit einem Passwort oder Base64-Codierungen).</description>
  <!-- This is the step's headline. It should be short, but precise. -->
  <headline lang="en">Tools Selection</headline>
  <headline lang="zh-CN">工具选择</headline>
  <headline lang="ru">Выбор инструментов</headline>
  <headline lang="de">Werkzeuge: Auswahl</headline>
  <!-- This is the step's description. -->
  <task lang="en">Select a tool.</task>
  <task lang="zh-CN">选择一个工具。</task>
  <task lang="ru">Выберите инструмент.</task>
  <task lang="de">Wählen Sie eine Aufgabe.</task>
  <!-- AES-PKS5 input -->
  <input image="EnDeCrypt">
    <name lang="en">Encrypt with password</name>
    <name lang="zh-CN">用密码加密</name>
    <name lang="ru">Шифрование паролем</name>
    <name lang="de">Verschlüsseln mit Passwort</name>
    <description lang="en">Select this to quickly encrypt or decrypt some plaintext with AES by using a simple password. The encrypted result is base64-encoded text (e.g. for easy copy and paste to an email).</description>
    <description lang="zh-CN">选择此选项可使用简单的密码使用AES快速加密或解密某些纯文本。加密结果是base64编码的文本（例如，便于复制和粘贴到电子邮件中）。</description>
    <description lang="ru">Выберите это, чтобы быстро зашифровать или расшифровать некоторый открытый текст с помощью AES с помощью простого пароля. Зашифрованный результат - текст с кодировкой base64 (например, для удобства копирования и вставки в электронную почту).</description>
    <description lang="de">Hier können Sie einen Text mit Hilfe eines Passwortes verschlüsseln (AES). Das verschlüsselte Ergebnis wird als Base-64-codierter Text ausgegeben – dadurch kann die Ausgabe sehr einfach z.B. in eine E-Mail kopiert werden.</description>
    <headline lang="en">Message Input</headline>
    <headline lang="zh-CN">留言输入</headline>
    <headline lang="ru">Ввод сообщений</headline>
    <headline lang="de">Nachrichteneingabe</headline>
    <task lang="en">Here, you can enter your message and the password to use. The password is converted to a 256-bit AES key by using PKCS5. The entered message is then encrypted or decrypted using AES-256.</task>
    <task lang="zh-CN">在这里，您可以输入您的信息和密码。使用PKCS5将密码转换为256位AES密钥。然后使用AES-256对输入的消息进行加密或解密。</task>
    <task lang="ru">Здесь вы можете ввести свое сообщение и пароль для использования. Пароль преобразуется в 256-битный ключ AES с помощью PKCS5. Введенное сообщение затем зашифровывается или дешифруется с использованием AES-256.</task>
    <task lang="de">Hier können Sie Ihre Nachricht und das Passwort eingeben. Das Passwort wird mittels PKCS5 zu einem 256-Bit AES-Schlüssel umgewandelt. Ihre Nachricht wird danach mit AES-256 ver- oder entschlüsselt.</task>
    <comboBox plugin="AES;$Switch$" property="Action" alignment="Left" width="20%" group="1">
      <description lang="en">Encrypt or Decrypt:</description>
      <description lang="zh-CN">加密或解密：</description>
      <description lang="ru">Шифрование или расшифровка:</description>
      <description lang="de">Verschlüsseln oder Entschlüsseln:</description>
      <item lang="en" content="Encrypt" />
      <item lang="zh-CN" content="加密" />
      <item lang="ru" content="шифровать" />
      <item lang="de" content="Verschlüsseln" />
      <item lang="en" content="Decrypt" />
      <item lang="zh-CN" content="解密" />
      <item lang="ru" content="расшифровывать" />
      <item lang="de" content="Entschlüsseln" />
    </comboBox>
    <inputBox plugin="$Password$" property="Text" alignment="Right" width="78%" visibleLines="1" group="1">
      <storage key="password" showLoadAddButtons="true" />
      <description lang="en">Password:</description>
      <description lang="zh-CN">密码：</description>
      <description lang="ru">Пароль:</description>
      <description lang="de">Passwort:</description>
      <defaultvalue>Your secret password or passphrase</defaultvalue>
    </inputBox>
    <inputBox plugin="$Input$" property="Text" alignment="Stretch" width="100%" visibleLines="15">
      <description lang="en">
        <condition plugin="AES;$Switch$" property="Action" value="0">
          Message to encrypt:
        </condition>
        <condition plugin="AES;$Switch$" property="Action" value="1">
          Message to decrypt:
        </condition>
      </description>
      <description lang="zh-CN">加密消息：解密消息：</description>
      <description lang="ru">Сообщение для шифрования: сообщение для расшифровки:</description>
      <description lang="de">
        <condition plugin="AES;$Switch$" property="Action" value="0">
          Zu verschlüsselnde Nachricht:
        </condition>
        <condition plugin="AES;$Switch$" property="Action" value="1">
          Zu entschlüsselnde Nachricht:
        </condition>
      </description>
      <defaultvalue>The quick brown fox jumps over the lazy dog.</defaultvalue>
    </inputBox>
    <sampleViewer image="AES" file="Cryptography\Modern\Symmetric\AES-CBC-IV-PKCS5-Base64.cwm">
      <name lang="en">Result</name>
      <name lang="zh-CN">结果</name>
      <name lang="ru">результат</name>
      <name lang="de">Ergebnis</name>
      <description lang="en">-</description>
      <description lang="zh-CN">--</description>
      <description lang="ru">-</description>
      <description lang="de">-</description>
      <headline lang="en">Your message</headline>
      <headline lang="zh-CN">你的信息</headline>
      <headline lang="ru">Ваше сообщение</headline>
      <headline lang="de">Ihre Nachricht</headline>
      <task lang="en">
        <condition plugin="AES;$Switch$" property="Action" value="0">
          Your encrypted message. The encrypted result is base-64-encoded, which is convenient when copied e.g. to an email. The receiver can then use the same procedure (and clearly the same password) to get back the original message.
        </condition>
        <condition plugin="AES;$Switch$" property="Action" value="1">
          Your decrypted message.
        </condition>
      </task>
      <task lang="zh-CN">您的加密邮件。加密结果是base-64编码的，这在复制到例如电子邮件中时非常方便。然后，接收者可以使用相同的过程（并且显然使用相同的密码）来获取原始消息。您的解密邮件。</task>
      <task lang="ru">Ваше зашифрованное сообщение. Зашифрованный результат кодируется base-64, что удобно при копировании, например, в электронную почту. Затем получатель может использовать ту же процедуру (и, очевидно, тот же пароль), чтобы вернуть исходное сообщение. Ваше расшифрованное сообщение.</task>
      <task lang="de">
        <condition plugin="AES;$Switch$" property="Action" value="0">
          Hier sehen Sie Ihre verschlüsselte Nachricht. Die verschlüsselte Nachricht ist zusätzlich in Base64 codiert, wodurch ein einfaches Kopieren in z.B. eine E-Mail möglich ist. Der Empfänger kann mit der gleichen Auswahl (und natürlich dem gleichen Passwort) die empfangene Nachricht entschlüsseln.
        </condition>
        <condition plugin="AES;$Switch$" property="Action" value="1">
          Hier sehen Sie Ihre entschlüsselte Nachricht.
        </condition>
      </task>
      <presentation plugin="$Output$" height="150">
        <description lang="en">Message:</description>
        <description lang="zh-CN">信息：</description>
        <description lang="ru">Сообщение:</description>
        <description lang="de">Nachricht:</description>
      </presentation>
    </sampleViewer>
  </input>
  <!-- Password Strength input -->
  <input image="PasswordStrength">
    <name lang="en">Password Strength</name>
    <name lang="zh-CN">密码强度</name>
    <name lang="ru">Надежность Пароля</name>
    <name lang="de">Passwort-Stärke</name>
    <description lang="en">Select this to test the strength of your password.</description>
    <description lang="zh-CN">选择此选项可测试您的密码强度。</description>
    <description lang="ru">Выберите это, чтобы проверить силу вашего пароля.</description>
    <description lang="de">Hier können Sie die Stärke Ihres Passwortes testen.</description>
    <headline lang="en">Password Input</headline>
    <headline lang="zh-CN">密码输入</headline>
    <headline lang="ru">Ввод пароля</headline>
    <headline lang="de">Passwort-Eingabe</headline>
    <task lang="en">Here, you can enter your password to test its strength. Warning! Password is visible on the screen.</task>
    <task lang="zh-CN">在这里，您可以输入密码以测试其强度。警告！密码在屏幕上可见。</task>
    <task lang="ru">Здесь вы можете ввести свой пароль, чтобы проверить его прочность. Предупреждение! На экране отображается пароль.</task>
    <task lang="de">Hier können Sie Ihr Passwort eingeben, um dessen Stärke zu ermitteln. Warnung! Das Passwort ist auf dem Bildschirm lesbar.</task>
    <inputBox plugin="$Password$" property="Text" alignment="Right" width="78%" visibleLines="1" group="1">
      <storage key="password" showLoadAddButtons="true" />
      <description lang="en">Password (cleartext!) :</description>
      <description lang="zh-CN">密码（明文！）：</description>
      <description lang="ru">Пароль (очистить!):</description>
      <description lang="de">Passwort (Klartext!) :</description>
      <defaultvalue>test105!A</defaultvalue>
    </inputBox>
